# -*- coding: utf-8 -*-
"""day4_practice_questions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YkXVmETM10PGQ-TeqWgPMB-VslrN2p4V
"""

#1
pip install numpy

#2
import numpy as np

#3
arr=np.array([1,2,3,4,5])
print(arr)

#4
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

#5
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

#6
arr=np.array([1,2,3,4,5,6,7,8,9],ndmin=2)
print(arr)

#7
r=3
c=4
ran=np.random.rand(r,c)
print(ran)

#8
shape=(3,4)
arr=np.zeros(shape)
print(arr)

#9
shape=(3,4)
arr=np.ones(shape)
print(arr)

#10
arr=np.empty((3,3))
print(arr)

#11
arr=np.arange(1,13,4)
print(arr)

#12
arr=np.linspace(0,1,11)
arr

#13
np.array([[1,2,3],[4,5,6]]).shape

#14
arr = np.array([[1, 2, 3], [4, 5, 6]])
ele=arr.size
print(ele)

#15
np.array([[1,2,3],[4,5,6]]).shape

#16
arr=np.array([1,2,3,4,5])
ele=arr.astype(float)
print(ele)

#17
arr=np.array([1.2,1.9,23.32])
ele=arr.astype(int)
print(ele)

#18
arr=[3,7,1,8,4,6,0,2,5]
maxi=np.max(arr)
mini=np.min(arr)
print(maxi,mini)

#19
arr=np.array([3,7,1,8,4,6,0,2,5])
new=arr.reshape(3,3)
print(new)

#20
arr=np.array([3,7,1,8,4,6,0,2,5])
ele=np.array_split(arr,3)
print(ele)

#21
arr=np.array([[3,7],[1,8]])
hs=np.hsplit(arr,2)
print(hs)
vs=np.chatvsplit(arr,2)
print(vs)

#22
arr=np.array([1,2,3,4,5,6],ndmin=5)
print(arr)
ele=arr.reshape(3,2)
print(ele)

#23
arr=np.array([3,7,1,8,4,6,0,2,5])
ele=arr.flatten()
print(ele)

#24
arr=np.array([3,7,1,8,4,6,0,2,5])

print(np.sort(arr))

#25
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
ar3=np.concatenate((arr1,arr2),axis=0)
print(ar3)

#26
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=arr1+arr2
print(arr3)

#27
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=arr1**arr2
print(arr3)

#28
arr1=np.array([1,2,3])
print(np.sum(arr1))
print(np.mean(arr1))
print(np.median(arr1))

#29
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

arr2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])
print(np.dot(arr1,arr2))

#30
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(arr1.T)

#31
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

arr2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])
print(np.dot(arr1,arr2))

#32
arr1 = np.array([[1, 2],
                    [4, 6]])
print(np.linalg.inv(arr1))

#33
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

arr2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])
print(np.dot(arr1,arr2))

#34
use np.nan

#35
arr1=np.array([1,2,3,4])
print(np.where(arr1==4))

#36
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

arr2 = np.array([[7, 8,11],
                    [9, 10,12,]
                    ])
arr3=arr1*arr2
print(arr3)

#37
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
arr=np.mean(arr1,axis=1)
arr3=np.median(arr1,axis=1)
print(arr,arr3)

#38
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
arr=np.std(arr1)
arr2=np.std((arr1),ddof=1)

print(arr,arr2)

#39

arr=np.array([1,2,3,'hemanth',5.77])
x=arr.copy() # it makes a copy of the array
x[0]=9
print(arr)
print(x)
print(x.base)

y=arr.view # it creates a view, any chnage in array , it happens in view
arr[0]=9
print(arr)
print(y)

#40
arr=np.array([1,2,3,4,5])
arr[:2]

#41
arr=np.array([1,2,3,4,5])
print(np.where(arr==3))

#42
arr=np.array([1,2,3,4,5])
arr[:5]

#43
arr=np.array([1,2,3,4,5])
arr[::2]

#44
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(arr1[:,1])

#45
arr=np.array([[1,2],[3,4]])
arr[::-1]

#46
arr=np.array([[1,2],[3,4]])
np.diagonal(arr)

#47
arr=np.array([True, False, True, False])
arr[:2]

#48
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
arr=arr1[arr1>2]
print(arr)

#49
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[:,1]